version:  '3.8'

services:
    database:
        image: mysql:5.7
        restart: on-failure
        ports:
            - '3301:3306'
        container_name: recombee_db
        environment:
            MYSQL_ROOT_PASSWORD: Root12345!
            MYSQL_DATABASE: recombee_db
        networks:
            - RECOMBEE_NETWORK
        volumes:
            - ./docker/db/data:/var/lib/mysql
    php:
        container_name: recombee_php
        environment:
            - DATABASE_URL=mysql://root:Root12345!@database/recombee_db?serverVersion=5.7
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - '.:/usr/src/app'
        restart: on-failure
        env_file:
            - .env
        depends_on:
            - database
        networks:
            - RECOMBEE_NETWORK
    nginx:
        container_name: recombee_nginx
        image: nginx:1.19.0-alpine
        restart: on-failure
        volumes:
            - './public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '8010:80'
        depends_on:
            - php
        networks:
            - RECOMBEE_NETWORK

networks:
    RECOMBEE_NETWORK:
        name: ${RECOMBEE_NETWORK}
